
FROM rust:latest

WORKDIR /app

RUN rustup component add llvm-tools-preview \
    && cargo install cargo-llvm-cov

COPY Cargo.toml Cargo.lock ./
COPY src ./src

CMD ["sh", "-c", "cargo llvm-cov clean && cargo llvm-cov --workspace --all-features --ignore-filename-regex '.*_test\\.rs$' --fail-under-lines 95"]
